# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Data Tutorial
tagline:          ''
description:      'hi, I am Tan, this site is my practical experience while I do data science.'
url:              http://datatutorial.com
baseurl:          '/'

author:
  name:           'Tan Pham'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tanpv
